// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package orderdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID           string             `json:"order_id"`
	CustomerID        string             `json:"customer_id"`
	Symbol            string             `json:"symbol"`
	Side              string             `json:"side"`
	Price             pgtype.Numeric     `json:"price"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	RemainingQuantity pgtype.Numeric     `json:"remaining_quantity"`
	Status            string             `json:"status"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	CanceledAt        pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type OrderOutbox struct {
	ID            string             `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Topic         string             `json:"topic"`
	PartitionKey  string             `json:"partition_key"`
	Payload       []byte             `json:"payload"`
	RetryCount    int32              `json:"retry_count"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}
