// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package orderdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  id,
  customer_id,
  symbol,
  side,
  price,
  quantity,
  remaining_quantity,
  status,
  idempotency_key,
  canceled_at,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $6,
  $7,
  $8,
  $9,
  COALESCE($10, NOW()),
  NOW()
)
RETURNING id, customer_id, symbol, side, price, quantity, remaining_quantity, status, idempotency_key, canceled_at, created_at, updated_at
`

type CreateOrderParams struct {
	ID             string             `json:"id"`
	CustomerID     string             `json:"customer_id"`
	Symbol         string             `json:"symbol"`
	Side           string             `json:"side"`
	Price          pgtype.Numeric     `json:"price"`
	Quantity       pgtype.Numeric     `json:"quantity"`
	Status         string             `json:"status"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt      interface{}        `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.CustomerID,
		arg.Symbol,
		arg.Side,
		arg.Price,
		arg.Quantity,
		arg.Status,
		arg.IdempotencyKey,
		arg.CanceledAt,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Symbol,
		&i.Side,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Status,
		&i.IdempotencyKey,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListOrdersByCustomerID = `-- name: GetListOrdersByCustomerID :many
SELECT id, customer_id, symbol, side, price, quantity, remaining_quantity, status, idempotency_key, canceled_at, created_at, updated_at
FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetListOrdersByCustomerIDParams struct {
	CustomerID string `json:"customer_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetListOrdersByCustomerID(ctx context.Context, arg GetListOrdersByCustomerIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getListOrdersByCustomerID, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Symbol,
			&i.Side,
			&i.Price,
			&i.Quantity,
			&i.RemainingQuantity,
			&i.Status,
			&i.IdempotencyKey,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, symbol, side, price, quantity, remaining_quantity, status, idempotency_key, canceled_at, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Symbol,
		&i.Side,
		&i.Price,
		&i.Quantity,
		&i.RemainingQuantity,
		&i.Status,
		&i.IdempotencyKey,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
