// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package orderdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  order_id,
  customer_id,
  symbol,
  side,
  price_cents,
  quantity_units,
  remaining_quantity_units,
  status,
  idempotency_key,
  canceled_at,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $6,
  $7,
  $8,
  $9,
  COALESCE($10, NOW()),
  NOW()
)
RETURNING order_id, customer_id, symbol, side, price_cents, quantity_units, remaining_quantity_units, status, idempotency_key, canceled_at, created_at, updated_at
`

type CreateOrderParams struct {
	OrderID        string             `json:"order_id"`
	CustomerID     string             `json:"customer_id"`
	Symbol         string             `json:"symbol"`
	Side           string             `json:"side"`
	PriceCents     int64              `json:"price_cents"`
	QuantityUnits  int64              `json:"quantity_units"`
	Status         string             `json:"status"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt      interface{}        `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderID,
		arg.CustomerID,
		arg.Symbol,
		arg.Side,
		arg.PriceCents,
		arg.QuantityUnits,
		arg.Status,
		arg.IdempotencyKey,
		arg.CanceledAt,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.CustomerID,
		&i.Symbol,
		&i.Side,
		&i.PriceCents,
		&i.QuantityUnits,
		&i.RemainingQuantityUnits,
		&i.Status,
		&i.IdempotencyKey,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListOrdersByCustomerID = `-- name: GetListOrdersByCustomerID :many
SELECT order_id, customer_id, symbol, side, price_cents, quantity_units, remaining_quantity_units, status, idempotency_key, canceled_at, created_at, updated_at
FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetListOrdersByCustomerIDParams struct {
	CustomerID string `json:"customer_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetListOrdersByCustomerID(ctx context.Context, arg GetListOrdersByCustomerIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getListOrdersByCustomerID, arg.CustomerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.CustomerID,
			&i.Symbol,
			&i.Side,
			&i.PriceCents,
			&i.QuantityUnits,
			&i.RemainingQuantityUnits,
			&i.Status,
			&i.IdempotencyKey,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT order_id, customer_id, symbol, side, price_cents, quantity_units, remaining_quantity_units, status, idempotency_key, canceled_at, created_at, updated_at
FROM orders
WHERE order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.CustomerID,
		&i.Symbol,
		&i.Side,
		&i.PriceCents,
		&i.QuantityUnits,
		&i.RemainingQuantityUnits,
		&i.Status,
		&i.IdempotencyKey,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderExecution = `-- name: UpdateOrderExecution :execrows
UPDATE orders
SET remaining_quantity_units = $1,
    status = $2,
    updated_at = NOW()
WHERE order_id = $3
  AND status = 'PENDING'
`

type UpdateOrderExecutionParams struct {
	RemainingQuantityUnits int64  `json:"remaining_quantity_units"`
	Status                 string `json:"status"`
	OrderID                string `json:"order_id"`
}

func (q *Queries) UpdateOrderExecution(ctx context.Context, arg UpdateOrderExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderExecution, arg.RemainingQuantityUnits, arg.Status, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
