// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package orderdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :execrows
UPDATE orders
SET status = 'CANCELED',
    canceled_at = NOW(),
    updated_at = NOW()
WHERE order_id = $1
  AND status = $2
`

type CancelOrderParams struct {
	OrderID        string `json:"order_id"`
	PreviousStatus string `json:"previous_status"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOrder, arg.OrderID, arg.PreviousStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimUnpublishedOutboxEvents = `-- name: ClaimUnpublishedOutboxEvents :many
WITH candidates AS (
  SELECT order_outbox.id, order_outbox.created_at
  FROM order_outbox
  WHERE order_outbox.published_at IS NULL
    AND (
      order_outbox.locked_at IS NULL
      OR order_outbox.locked_at < $1
    )
  ORDER BY order_outbox.created_at ASC
  LIMIT $2
  FOR UPDATE SKIP LOCKED
),
claimed AS (
  UPDATE order_outbox
  SET locked_at = NOW(),
      locked_by = $3
  WHERE order_outbox.id IN (SELECT candidates.id FROM candidates)
  RETURNING id, aggregate_type, aggregate_id, event_type, topic, partition_key, payload, retry_count, last_error, locked_at, locked_by, created_at, published_at
)
SELECT claimed.id, claimed.aggregate_type, claimed.aggregate_id, claimed.event_type, claimed.topic, claimed.partition_key, claimed.payload, claimed.retry_count, claimed.last_error, claimed.locked_at, claimed.locked_by, claimed.created_at, claimed.published_at
FROM claimed
JOIN candidates ON candidates.id = claimed.id
ORDER BY candidates.created_at ASC
`

type ClaimUnpublishedOutboxEventsParams struct {
	ReclaimBefore pgtype.Timestamptz `json:"reclaim_before"`
	LimitCount    int32              `json:"limit_count"`
	LockedBy      pgtype.Text        `json:"locked_by"`
}

type ClaimUnpublishedOutboxEventsRow struct {
	ID            string             `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   string             `json:"aggregate_id"`
	EventType     string             `json:"event_type"`
	Topic         string             `json:"topic"`
	PartitionKey  string             `json:"partition_key"`
	Payload       []byte             `json:"payload"`
	RetryCount    int32              `json:"retry_count"`
	LastError     pgtype.Text        `json:"last_error"`
	LockedAt      pgtype.Timestamptz `json:"locked_at"`
	LockedBy      pgtype.Text        `json:"locked_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) ClaimUnpublishedOutboxEvents(ctx context.Context, arg ClaimUnpublishedOutboxEventsParams) ([]ClaimUnpublishedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, claimUnpublishedOutboxEvents, arg.ReclaimBefore, arg.LimitCount, arg.LockedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimUnpublishedOutboxEventsRow{}
	for rows.Next() {
		var i ClaimUnpublishedOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Topic,
			&i.PartitionKey,
			&i.Payload,
			&i.RetryCount,
			&i.LastError,
			&i.LockedAt,
			&i.LockedBy,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  order_id,
  symbol,
  side,
  price_cents,
  quantity_units,
  remaining_quantity_units,
  status,
  idempotency_key,
  canceled_at,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $5,
  $6,
  $7,
  $8,
  COALESCE($9, NOW()),
  NOW()
)
RETURNING order_id, symbol, side, price_cents, quantity_units, remaining_quantity_units, status, idempotency_key, canceled_at, created_at, updated_at
`

type CreateOrderParams struct {
	OrderID        string             `json:"order_id"`
	Symbol         string             `json:"symbol"`
	Side           string             `json:"side"`
	PriceCents     int64              `json:"price_cents"`
	QuantityUnits  int64              `json:"quantity_units"`
	Status         string             `json:"status"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CanceledAt     pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt      interface{}        `json:"created_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OrderID,
		arg.Symbol,
		arg.Side,
		arg.PriceCents,
		arg.QuantityUnits,
		arg.Status,
		arg.IdempotencyKey,
		arg.CanceledAt,
		arg.CreatedAt,
	)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.Symbol,
		&i.Side,
		&i.PriceCents,
		&i.QuantityUnits,
		&i.RemainingQuantityUnits,
		&i.Status,
		&i.IdempotencyKey,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO order_outbox (
  id,
  aggregate_type,
  aggregate_id,
  event_type,
  topic,
  partition_key,
  payload
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type CreateOutboxEventParams struct {
	ID            string `json:"id"`
	AggregateType string `json:"aggregate_type"`
	AggregateID   string `json:"aggregate_id"`
	EventType     string `json:"event_type"`
	Topic         string `json:"topic"`
	PartitionKey  string `json:"partition_key"`
	Payload       []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Topic,
		arg.PartitionKey,
		arg.Payload,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT order_id, symbol, side, price_cents, quantity_units, remaining_quantity_units, status, idempotency_key, canceled_at, created_at, updated_at
FROM orders
WHERE order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.Symbol,
		&i.Side,
		&i.PriceCents,
		&i.QuantityUnits,
		&i.RemainingQuantityUnits,
		&i.Status,
		&i.IdempotencyKey,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT order_id, symbol, side, price_cents, quantity_units, remaining_quantity_units, status, idempotency_key, canceled_at, created_at, updated_at
FROM orders
WHERE idempotency_key = $1
`

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, idempotencyKey)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.Symbol,
		&i.Side,
		&i.PriceCents,
		&i.QuantityUnits,
		&i.RemainingQuantityUnits,
		&i.Status,
		&i.IdempotencyKey,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :execrows
UPDATE order_outbox
SET retry_count = retry_count + 1,
    last_error = $1,
    locked_at = NULL,
    locked_by = NULL
WHERE id = $2
  AND locked_by = $3
  AND published_at IS NULL
`

type MarkOutboxEventFailedParams struct {
	LastError pgtype.Text `json:"last_error"`
	ID        string      `json:"id"`
	LockedBy  pgtype.Text `json:"locked_by"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventFailed, arg.LastError, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :execrows
UPDATE order_outbox
SET published_at = NOW(),
    last_error = NULL,
    locked_at = NULL,
    locked_by = NULL
WHERE id = $1
  AND locked_by = $2
  AND published_at IS NULL
`

type MarkOutboxEventPublishedParams struct {
	ID       string      `json:"id"`
	LockedBy pgtype.Text `json:"locked_by"`
}

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxEventPublished, arg.ID, arg.LockedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOrderExecution = `-- name: UpdateOrderExecution :execrows
UPDATE orders
SET remaining_quantity_units = $1,
    status = $2,
    updated_at = NOW()
WHERE order_id = $3
  AND status = $4
`

type UpdateOrderExecutionParams struct {
	RemainingQuantityUnits int64  `json:"remaining_quantity_units"`
	Status                 string `json:"status"`
	OrderID                string `json:"order_id"`
	PreviousStatus         string `json:"previous_status"`
}

func (q *Queries) UpdateOrderExecution(ctx context.Context, arg UpdateOrderExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderExecution,
		arg.RemainingQuantityUnits,
		arg.Status,
		arg.OrderID,
		arg.PreviousStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
