// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: market_data.sql

package marketdatadb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOrderBookLevel = `-- name: DeleteOrderBookLevel :exec
DELETE FROM market_order_book_levels
WHERE symbol_id = $1
  AND side = $2
  AND price_cents = $3
`

type DeleteOrderBookLevelParams struct {
	SymbolID   string `json:"symbol_id"`
	Side       string `json:"side"`
	PriceCents int64  `json:"price_cents"`
}

func (q *Queries) DeleteOrderBookLevel(ctx context.Context, arg DeleteOrderBookLevelParams) error {
	_, err := q.db.Exec(ctx, deleteOrderBookLevel, arg.SymbolID, arg.Side, arg.PriceCents)
	return err
}

const getLatestPrice = `-- name: GetLatestPrice :one
SELECT symbol_id, symbol, price_cents, updated_at
FROM market_latest_prices
WHERE symbol = $1
`

func (q *Queries) GetLatestPrice(ctx context.Context, symbol string) (MarketLatestPrice, error) {
	row := q.db.QueryRow(ctx, getLatestPrice, symbol)
	var i MarketLatestPrice
	err := row.Scan(
		&i.SymbolID,
		&i.Symbol,
		&i.PriceCents,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderBookAsks = `-- name: GetOrderBookAsks :many
SELECT symbol_id, symbol, side, price_cents, quantity_units, order_count, updated_at
FROM market_order_book_levels
WHERE symbol = $1
  AND side = 'ASK'
  AND quantity_units > 0
  AND order_count > 0
ORDER BY price_cents ASC
LIMIT $2
`

type GetOrderBookAsksParams struct {
	Symbol string `json:"symbol"`
	Depth  int32  `json:"depth"`
}

func (q *Queries) GetOrderBookAsks(ctx context.Context, arg GetOrderBookAsksParams) ([]MarketOrderBookLevel, error) {
	rows, err := q.db.Query(ctx, getOrderBookAsks, arg.Symbol, arg.Depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketOrderBookLevel{}
	for rows.Next() {
		var i MarketOrderBookLevel
		if err := rows.Scan(
			&i.SymbolID,
			&i.Symbol,
			&i.Side,
			&i.PriceCents,
			&i.QuantityUnits,
			&i.OrderCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderBookBids = `-- name: GetOrderBookBids :many
SELECT symbol_id, symbol, side, price_cents, quantity_units, order_count, updated_at
FROM market_order_book_levels
WHERE symbol = $1
  AND side = 'BID'
  AND quantity_units > 0
  AND order_count > 0
ORDER BY price_cents DESC
LIMIT $2
`

type GetOrderBookBidsParams struct {
	Symbol string `json:"symbol"`
	Depth  int32  `json:"depth"`
}

func (q *Queries) GetOrderBookBids(ctx context.Context, arg GetOrderBookBidsParams) ([]MarketOrderBookLevel, error) {
	rows, err := q.db.Query(ctx, getOrderBookBids, arg.Symbol, arg.Depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketOrderBookLevel{}
	for rows.Next() {
		var i MarketOrderBookLevel
		if err := rows.Scan(
			&i.SymbolID,
			&i.Symbol,
			&i.Side,
			&i.PriceCents,
			&i.QuantityUnits,
			&i.OrderCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentTrades = `-- name: GetRecentTrades :many
SELECT trade_id, symbol_id, symbol, price_cents, quantity_units, buy_order_id, sell_order_id, executed_at
FROM market_trades
WHERE symbol = $1
ORDER BY executed_at DESC
LIMIT $2
`

type GetRecentTradesParams struct {
	Symbol     string `json:"symbol"`
	LimitCount int32  `json:"limit_count"`
}

func (q *Queries) GetRecentTrades(ctx context.Context, arg GetRecentTradesParams) ([]MarketTrade, error) {
	rows, err := q.db.Query(ctx, getRecentTrades, arg.Symbol, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketTrade{}
	for rows.Next() {
		var i MarketTrade
		if err := rows.Scan(
			&i.TradeID,
			&i.SymbolID,
			&i.Symbol,
			&i.PriceCents,
			&i.QuantityUnits,
			&i.BuyOrderID,
			&i.SellOrderID,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTrade = `-- name: InsertTrade :exec
INSERT INTO market_trades (
  trade_id,
  symbol_id,
  symbol,
  price_cents,
  quantity_units,
  buy_order_id,
  sell_order_id,
  executed_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8
)
`

type InsertTradeParams struct {
	TradeID       string             `json:"trade_id"`
	SymbolID      string             `json:"symbol_id"`
	Symbol        string             `json:"symbol"`
	PriceCents    int64              `json:"price_cents"`
	QuantityUnits int64              `json:"quantity_units"`
	BuyOrderID    string             `json:"buy_order_id"`
	SellOrderID   string             `json:"sell_order_id"`
	ExecutedAt    pgtype.Timestamptz `json:"executed_at"`
}

func (q *Queries) InsertTrade(ctx context.Context, arg InsertTradeParams) error {
	_, err := q.db.Exec(ctx, insertTrade,
		arg.TradeID,
		arg.SymbolID,
		arg.Symbol,
		arg.PriceCents,
		arg.QuantityUnits,
		arg.BuyOrderID,
		arg.SellOrderID,
		arg.ExecutedAt,
	)
	return err
}

const upsertLatestPrice = `-- name: UpsertLatestPrice :exec
INSERT INTO market_latest_prices (
  symbol_id,
  symbol,
  price_cents,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  COALESCE($4, NOW())
)
ON CONFLICT (symbol_id) DO UPDATE
SET symbol = EXCLUDED.symbol,
    price_cents = EXCLUDED.price_cents,
    updated_at = EXCLUDED.updated_at
`

type UpsertLatestPriceParams struct {
	SymbolID   string      `json:"symbol_id"`
	Symbol     string      `json:"symbol"`
	PriceCents int64       `json:"price_cents"`
	UpdatedAt  interface{} `json:"updated_at"`
}

func (q *Queries) UpsertLatestPrice(ctx context.Context, arg UpsertLatestPriceParams) error {
	_, err := q.db.Exec(ctx, upsertLatestPrice,
		arg.SymbolID,
		arg.Symbol,
		arg.PriceCents,
		arg.UpdatedAt,
	)
	return err
}

const upsertOrderBookLevel = `-- name: UpsertOrderBookLevel :exec
INSERT INTO market_order_book_levels (
  symbol_id,
  symbol,
  side,
  price_cents,
  quantity_units,
  order_count,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  COALESCE($7, NOW())
)
ON CONFLICT (symbol_id, side, price_cents) DO UPDATE
SET symbol = EXCLUDED.symbol,
    quantity_units = EXCLUDED.quantity_units,
    order_count = EXCLUDED.order_count,
    updated_at = EXCLUDED.updated_at
`

type UpsertOrderBookLevelParams struct {
	SymbolID      string      `json:"symbol_id"`
	Symbol        string      `json:"symbol"`
	Side          string      `json:"side"`
	PriceCents    int64       `json:"price_cents"`
	QuantityUnits int64       `json:"quantity_units"`
	OrderCount    int32       `json:"order_count"`
	UpdatedAt     interface{} `json:"updated_at"`
}

func (q *Queries) UpsertOrderBookLevel(ctx context.Context, arg UpsertOrderBookLevelParams) error {
	_, err := q.db.Exec(ctx, upsertOrderBookLevel,
		arg.SymbolID,
		arg.Symbol,
		arg.Side,
		arg.PriceCents,
		arg.QuantityUnits,
		arg.OrderCount,
		arg.UpdatedAt,
	)
	return err
}
