// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package marketdatadb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MarketLatestPrice struct {
	Symbol     string             `json:"symbol"`
	PriceCents int64              `json:"price_cents"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type MarketOrderBookLevel struct {
	Symbol        string             `json:"symbol"`
	Side          string             `json:"side"`
	PriceCents    int64              `json:"price_cents"`
	QuantityUnits int64              `json:"quantity_units"`
	OrderCount    int32              `json:"order_count"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MarketTrade struct {
	TradeID       string             `json:"trade_id"`
	Symbol        string             `json:"symbol"`
	PriceCents    int64              `json:"price_cents"`
	QuantityUnits int64              `json:"quantity_units"`
	BuyOrderID    string             `json:"buy_order_id"`
	SellOrderID   string             `json:"sell_order_id"`
	ExecutedAt    pgtype.Timestamptz `json:"executed_at"`
}
